name: eslint CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm i --ignore-scripts

      - name: Run ESLint
        uses: ninosaurus/eslint-check@v5
        with:
          eslint-config-path: "./application/assets/js/.eslintrc.json"
          custom-directory: "./application"
          repo-token: ${{secrets.GITHUB_TOKEN}}